import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import { copyFileSync, mkdirSync } from 'fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const cliBanner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
marp-extended CLI - Marp with extended syntax support
*/
`;

const prod = process.argv[2] === 'production';
const cliOnly = process.argv.includes('--cli');
const obsidianOnly = process.argv.includes('--obsidian');
// Default: build both unless one is explicitly specified
const buildCli = cliOnly || (!cliOnly && !obsidianOnly);
const buildObsidian = obsidianOnly || (!cliOnly && !obsidianOnly);

// Build Obsidian plugin
async function buildObsidianPlugin() {
  console.log('Building Obsidian plugin...');

  // Ensure output directory exists
  mkdirSync('dist/obsidian', { recursive: true });

  const context = await esbuild.context({
    banner: {
      js: banner,
    },
    entryPoints: ['src/obsidian/main.ts'],
    bundle: true,
    external: [
      'obsidian',
      'electron',
      '@codemirror/autocomplete',
      '@codemirror/collab',
      '@codemirror/commands',
      '@codemirror/language',
      '@codemirror/lint',
      '@codemirror/search',
      '@codemirror/state',
      '@codemirror/view',
      '@lezer/common',
      '@lezer/highlight',
      '@lezer/lr',
      'node:os',
      'node:process',
      ...builtins,
    ],
    format: 'cjs',
    target: 'es2018',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'dist/obsidian/main.js',
    minify: prod,
  });

  if (prod) {
    await context.rebuild();
    await context.dispose();

    // Copy static files to dist/obsidian
    copyFileSync('manifest.json', 'dist/obsidian/manifest.json');
    copyFileSync('styles.css', 'dist/obsidian/styles.css');
    copyFileSync('engine.js', 'dist/obsidian/engine.js');

    console.log('Obsidian plugin built successfully: dist/obsidian/');
  } else {
    await context.watch();
    console.log('Watching for changes...');
  }
}

// Build CLI
async function buildCliTool() {
  console.log('Building CLI...');

  await esbuild.build({
    banner: {
      js: cliBanner,
    },
    entryPoints: ['src/cli/index.ts'],
    bundle: true,
    platform: 'node',
    target: 'node18',
    format: 'cjs',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'dist/cli/index.js',
    minify: prod,
    // Node.js built-ins are external by default with platform: 'node'
  });

  console.log('CLI built successfully: dist/cli/index.js');
}

// Main build logic
async function main() {
  try {
    if (buildCli) {
      await buildCliTool();
    }

    if (buildObsidian) {
      await buildObsidianPlugin();
    }

    if (prod) {
      process.exit(0);
    }
  } catch (err) {
    console.error('Build failed:', err);
    process.exit(1);
  }
}

main();
